import{a as f,i as u,S as q}from"./assets/vendor-08b0e0f9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();function m(e,r){const n=e.map(({largeImageURL:s,webformatURL:t,tags:a,likes:c,views:b,downloads:L,comments:M})=>`<li class="gallery-item">
        <a href="${s}">
        <img class="gallery-image" src="${t}" alt="${a}">
            <ul class="gallery-item-description">
                <li>Likes: ${c}</li>
                <li>Views: ${b}</li>
                <li>Downloads: ${L}</li>
                <li>Comments: ${M}</li>
            </ul>
        </a>
    </li>`).join("");r.insertAdjacentHTML("beforeend",n)}f.defaults.baseURL="https://pixabay.com/api/";function g({query:e,page:r=1,per_page:n}){return f.get("",{params:{key:"41812412-8184544d67aaee5dc545e6a16",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}}).then(({data:s})=>s)}const d="hidden";function w(e){e.classList.add(d)}function B(e){e.classList.remove(d)}function v(e,r){r.classList.add(d),e.disabled=!1}function P(e,r){r.classList.remove(d),e.disabled=!0}const l={hide:w,show:B,enable:v,disable:P},o={searchForm:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.getElementById("loader"),loadMoreBtn:document.querySelector('[data-action="load-more"]')},i={query:"",page:1,maxPage:0,per_page:40};o.searchForm.addEventListener("submit",S);async function S(e){e.preventDefault(),o.gallery.innerHTML="",i.page=1,l.hide(o.loadMoreBtn);const r=e.currentTarget;if(i.query=r.elements.query.value.trim(),!!i.query)try{const{hits:n,totalHits:s}=await g(i);i.maxPage=Math.ceil(s/i.per_page),n.length===0&&u.error({message:"Sorry, there are no images matching your search query. Please try again!"}),m(n,o.gallery),n.length>0&&n.length!==s?(l.show(o.loadMoreBtn),o.loadMoreBtn.addEventListener("click",h)):l.hide(o.loadMoreBtn)}catch{y()}finally{r.reset(),p.refresh()}}async function h(){i.page+=1,l.disable(o.loadMoreBtn,o.loader);const e=document.querySelector(".gallery-item").getBoundingClientRect();try{const{hits:r}=await g(i);m(r,o.gallery)}catch{y()}finally{l.enable(o.loadMoreBtn,o.loader),p.refresh(),window.scrollBy({top:e.height*2,left:0,behavior:"smooth"}),i.page===i.maxPage&&(l.hide(o.loadMoreBtn),o.loadMoreBtn.removeEventListener("click",h),u.info({message:"We're sorry, but you've reached the end of search results."}))}}function y(e){u.error({message:"Sorry, something went wrong. Please try again later!"})}let p=new q(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
